sources:
  - name: in
    base_url: https://www.in.gr
    rss:
      - https://www.in.gr/feed/
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: tanea
    base_url: https://www.tanea.gr
    rss:
      - https://www.tanea.gr/feed/
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: news247
    base_url: https://www.news247.gr
    rss:
      - https://www.news247.gr/feed/
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: thetoc
    base_url: https://www.thetoc.gr
    rss:
      - https://www.thetoc.gr/feed/
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: protothema
    base_url: https://www.protothema.gr
    rss:
      - https://www.protothema.gr/rss.xml
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: skai
    base_url: https://www.skai.gr
    rss:
      - https://www.skai.gr/news/rss
    search_paths:
      - /?s={query}
      - /search/?q={query}

  - name: euro2day
    base_url: https://www.euro2day.gr
    rss:
      - https://www.euro2day.gr/ListRSS.aspx
    search_paths:
      - /search.aspx?search={query}

  - name: newsgr
    base_url: https://www.news.gr
    rss:
      - https://www.news.gr/rss-feed
    search_paths:
      - /?s={query}
      - /search/{query}